name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Générer le .exe
      run: |
        pyinstaller --onefile ton_script.py

    - name: Upload du fichier .exe
      uses: actions/upload-artifact@v4
      with:
        name: exe-windows
        path: dist/surfspotrecommander.exe

        name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile ton_script.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: exe
        path: dist/ton_script.exe
